use mc;
insert into MCCourses (CourName) values ("Algorithms");
insert into MCCourses (CourName) values ("Data Structures");
insert into MCCourses (CourName) values ("Programming 101");
insert into MCCourses (CourName) values ("Discrete Mathematics");
insert into MCCourses (CourName) values ("Logic Design");
insert into MCCourses (CourName) values ("RF Circuits");
insert into MCCourses (CourName) values ("Data Analytics");
insert into MCCourses (CourName) values ("IT Management");
insert into MCCourses (CourName) values ("Neural Networks");
